spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://dpg-conmi3i1hbls73flr2jg-a.frankfurt-postgres.render.com:5432/cw2db
#    username: postgres
    username: cw2db_user
#    password: postgres
    password: 80OUsazgh9RojwHfoakUVJTato8HJrkL

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  mail:
    host: smtp.mail.ru
    port: 465
    username: whynotpc@mail.ru
    password: b6ENcxjZDw6ASaGw95mM
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

application:
  security:
    jwt:
      secret-key: 34743777217A25432A462D4A614E645267556B58703273357638782F413F4428
      expiration: 86400000
#      expiration: 5000
      refresh-token:
        expiration: 604800000
#        expiration: 60000
#logging:
#  level:
#    org:
#      apache.coyote.http11.Http11Processor: TRACE
